2025-06-15 17:55:20,718 INFO    MainThread:1988577 [wandb_setup.py:_flush():67] Current SDK version is 0.19.9
2025-06-15 17:55:20,718 INFO    MainThread:1988577 [wandb_setup.py:_flush():67] Configure stats pid to 1988577
2025-06-15 17:55:20,718 INFO    MainThread:1988577 [wandb_setup.py:_flush():67] Loading settings from /home/user/.config/wandb/settings
2025-06-15 17:55:20,718 INFO    MainThread:1988577 [wandb_setup.py:_flush():67] Loading settings from /home/user/Desktop/kjy/DIFUSCO/wandb/settings
2025-06-15 17:55:20,718 INFO    MainThread:1988577 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-06-15 17:55:20,718 INFO    MainThread:1988577 [wandb_init.py:setup_run_log_directory():662] Logging user logs to /home/user/Desktop/kjy/DIFUSCO/data/models/wandb/offline-run-20250615_175520-q8cqiz4g/logs/debug.log
2025-06-15 17:55:20,718 INFO    MainThread:1988577 [wandb_init.py:setup_run_log_directory():663] Logging internal logs to /home/user/Desktop/kjy/DIFUSCO/data/models/wandb/offline-run-20250615_175520-q8cqiz4g/logs/debug-internal.log
2025-06-15 17:55:20,718 INFO    MainThread:1988577 [wandb_init.py:init():781] calling init triggers
2025-06-15 17:55:20,718 INFO    MainThread:1988577 [wandb_init.py:init():786] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-06-15 17:55:20,718 INFO    MainThread:1988577 [wandb_init.py:init():809] starting backend
2025-06-15 17:55:20,951 INFO    MainThread:1988577 [wandb_init.py:init():813] sending inform_init request
2025-06-15 17:55:20,992 INFO    MainThread:1988577 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-06-15 17:55:20,992 INFO    MainThread:1988577 [wandb_init.py:init():823] backend started and connected
2025-06-15 17:55:20,996 INFO    MainThread:1988577 [wandb_init.py:init():915] updated telemetry
2025-06-15 17:55:21,028 INFO    MainThread:1988577 [wandb_init.py:init():939] communicating run to backend with 90.0 second timeout
2025-06-15 17:55:21,108 INFO    MainThread:1988577 [wandb_init.py:init():1014] starting run threads in backend
2025-06-15 17:55:21,209 INFO    MainThread:1988577 [wandb_run.py:_console_start():2454] atexit reg
2025-06-15 17:55:21,210 INFO    MainThread:1988577 [wandb_run.py:_redirect():2306] redirect: wrap_raw
2025-06-15 17:55:21,210 INFO    MainThread:1988577 [wandb_run.py:_redirect():2371] Wrapping output streams.
2025-06-15 17:55:21,210 INFO    MainThread:1988577 [wandb_run.py:_redirect():2394] Redirects installed.
2025-06-15 17:55:21,212 INFO    MainThread:1988577 [wandb_init.py:init():1056] run started, returning control to user process
2025-06-15 17:55:24,116 INFO    MsgRouterThr:1988577 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 0 handles.
2025-06-15 17:55:24,268 ERROR   MainThread:1988577 [redirect.py:_on_write():661] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/difusco2/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/user/anaconda3/envs/difusco2/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2375, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/home/user/anaconda3/envs/difusco2/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/user/anaconda3/envs/difusco2/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/user/anaconda3/envs/difusco2/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/user/anaconda3/envs/difusco2/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/user/anaconda3/envs/difusco2/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/user/anaconda3/envs/difusco2/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/user/anaconda3/envs/difusco2/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/user/anaconda3/envs/difusco2/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/user/anaconda3/envs/difusco2/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/user/anaconda3/envs/difusco2/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-15 17:55:24,269 ERROR   MainThread:1988577 [redirect.py:_on_write():661] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/difusco2/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/user/anaconda3/envs/difusco2/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2375, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/home/user/anaconda3/envs/difusco2/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/user/anaconda3/envs/difusco2/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/user/anaconda3/envs/difusco2/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/user/anaconda3/envs/difusco2/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/user/anaconda3/envs/difusco2/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/user/anaconda3/envs/difusco2/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/user/anaconda3/envs/difusco2/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/user/anaconda3/envs/difusco2/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/user/anaconda3/envs/difusco2/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/user/anaconda3/envs/difusco2/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
